#!/bin/sh

# Lets Encrypt
if [ -z "$DOMAIN" ]; then
 echo "You need to have \$DOMAIN set"
else
 if [ -f /etc/letsencrypt/live/${DOMAIN}/fullchain.pem ]; then
  certbot renew
  kill -QUIT `cat/run/apache2/httpd.pid`
  rm -f /run/apache2/httpd.pid
  exec /usr/local/bin/httpd-foreground
 else
  echo "There is no cert to renew"
 fi
fi
